# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.

modLoader="javafml" #mandatory

loaderVersion="[28,)" #mandatory (28 is current forge version)

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="machinetest"

version="${file.jarVersion}" #mandatory

displayName="Example Mod" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="http://example.com/" #optional

logoFile="examplemod.png" #optional

credits="Everyone who helps me learn more about modding"

authors=" Drizzs "

description='''

Used to test machines for main mod

'''
